// API Configuration - Point this to your Flask backend running in VS Code
const API_BASE_URL = 'http://localhost:5000/api';

// Interfaces
export interface User {
  id: string;
  name: string;
  email: string;
  avatar?: string;
  createdAt: string;
}

export interface Goal {
  id: string;
  title: string;
  description: string;
  category: 'health' | 'career' | 'wellness' | 'relationships' | 'personal';
  targetDate?: string;
  createdAt: string;
  progress: number;
}

export interface Habit {
  id: string;
  title: string;
  description?: string;
  category: 'health' | 'productivity' | 'mindfulness' | 'social' | 'learning';
  frequency: 'daily' | 'weekly' | 'custom';
  completedDates: string[];
  streak: number;
  createdAt: string;
  goalId?: string;
  icon?: string;
  color?: string;
}

export interface Task {
  id: string;
  title: string;
  description?: string;
  completed: boolean;
  date: string;
  habitId?: string;
  goalId?: string;
  priority: 'low' | 'medium' | 'high';
  createdAt: string;
}

export interface JournalEntry {
  id: string;
  date: string;
  content: string;
  mood: 'great' | 'good' | 'okay' | 'low' | 'difficult';
  tags: string[];
  autoGenerated: boolean;
  chatSummary?: string;
  reflectionSummary?: string;
  createdAt: string;
}

export interface Reflection {
  id: string;
  date: string;
  wins: string[];
  challenges: string[];
  gratitude: string[];
  lessonsLearned: string;
  mood: 'great' | 'good' | 'okay' | 'low' | 'difficult';
  energyLevel: number;
  createdAt: string;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
}

export interface Achievement {
  id: string;
  title: string;
  description: string;
  icon: string;
  unlockedAt?: string;
  category: 'streak' | 'milestone' | 'special';
}

export interface Settings {
  notifications: boolean;
  morningPrepTime: string;
  eveningReflectionTime: string;
  theme: 'light' | 'dark' | 'system';
  privacy: {
    shareAnalytics: boolean;
    showStreak: boolean;
  };
}

// Helper for API calls
async function apiCall<T>(endpoint: string, options?: RequestInit): Promise<T> {
  const response = await fetch(`${API_BASE_URL}${endpoint}`, {
    headers: { 'Content-Type': 'application/json' },
    ...options,
  });
  if (!response.ok) {
    throw new Error(`API Error: ${response.statusText}`);
  }
  return response.json();
}

const getToday = () => new Date().toISOString().split('T')[0];

// ========== USER ==========
export async function getUser(): Promise<User | null> {
  try {
    return await apiCall<User>('/user');
  } catch {
    return null;
  }
}

export async function setUser(user: User): Promise<void> {
  await apiCall('/user', {
    method: 'PUT',
    body: JSON.stringify(user),
  });
}

export async function createUser(name: string, email: string, password: string): Promise<User> {
  return await apiCall<User>('/user', {
    method: 'POST',
    body: JSON.stringify({ name, email, password }),
  });
}

export async function loginUser(email: string, password: string): Promise<User | null> {
  try {
    return await apiCall<User>('/user/login', {
      method: 'POST',
      body: JSON.stringify({ email, password }),
    });
  } catch {
    return null;
  }
}

export async function logoutUser(): Promise<void> {
  await apiCall('/user/logout', { method: 'POST' });
}

// ========== GOALS ==========
export async function getGoals(): Promise<Goal[]> {
  try {
    return await apiCall<Goal[]>('/goals');
  } catch {
    return [];
  }
}

export async function saveGoals(goals: Goal[]): Promise<void> {
  await apiCall('/goals', {
    method: 'PUT',
    body: JSON.stringify(goals),
  });
}

export async function addGoal(goal: Omit<Goal, 'id' | 'createdAt' | 'progress'>): Promise<Goal> {
  return await apiCall<Goal>('/goals', {
    method: 'POST',
    body: JSON.stringify(goal),
  });
}

export async function updateGoal(id: string, updates: Partial<Goal>): Promise<void> {
  await apiCall(`/goals/${id}`, {
    method: 'PUT',
    body: JSON.stringify(updates),
  });
}

export async function deleteGoal(id: string): Promise<void> {
  await apiCall(`/goals/${id}`, { method: 'DELETE' });
}

// ========== HABITS ==========
export async function getHabits(): Promise<Habit[]> {
  try {
    return await apiCall<Habit[]>('/habits');
  } catch {
    return [];
  }
}

export async function saveHabits(habits: Habit[]): Promise<void> {
  await apiCall('/habits', {
    method: 'PUT',
    body: JSON.stringify(habits),
  });
}

export async function addHabit(habit: Omit<Habit, 'id' | 'createdAt' | 'completedDates' | 'streak'>): Promise<Habit> {
  return await apiCall<Habit>('/habits', {
    method: 'POST',
    body: JSON.stringify(habit),
  });
}

export async function completeHabit(id: string): Promise<void> {
  await apiCall(`/habits/${id}/complete`, { method: 'POST' });
}

export async function uncompleteHabit(id: string): Promise<void> {
  await apiCall(`/habits/${id}/uncomplete`, { method: 'POST' });
}

export async function deleteHabit(id: string): Promise<void> {
  await apiCall(`/habits/${id}`, { method: 'DELETE' });
}

// ========== TASKS ==========
export async function getTasks(date?: string): Promise<Task[]> {
  try {
    const endpoint = date ? `/tasks?date=${date}` : '/tasks';
    return await apiCall<Task[]>(endpoint);
  } catch {
    return [];
  }
}

export async function saveTasks(tasks: Task[]): Promise<void> {
  await apiCall('/tasks', {
    method: 'PUT',
    body: JSON.stringify(tasks),
  });
}

export async function addTask(task: Omit<Task, 'id' | 'createdAt'>): Promise<Task> {
  return await apiCall<Task>('/tasks', {
    method: 'POST',
    body: JSON.stringify(task),
  });
}

export async function toggleTask(id: string): Promise<void> {
  await apiCall(`/tasks/${id}/toggle`, { method: 'POST' });
}

export async function deleteTask(id: string): Promise<void> {
  await apiCall(`/tasks/${id}`, { method: 'DELETE' });
}

// ========== JOURNAL ==========
export async function getJournalEntries(): Promise<JournalEntry[]> {
  try {
    return await apiCall<JournalEntry[]>('/journal');
  } catch {
    return [];
  }
}

export async function saveJournalEntries(entries: JournalEntry[]): Promise<void> {
  await apiCall('/journal', {
    method: 'PUT',
    body: JSON.stringify(entries),
  });
}

export async function addJournalEntry(entry: Omit<JournalEntry, 'id' | 'createdAt'>): Promise<JournalEntry> {
  return await apiCall<JournalEntry>('/journal', {
    method: 'POST',
    body: JSON.stringify(entry),
  });
}

export async function getJournalByDate(date: string): Promise<JournalEntry | undefined> {
  try {
    return await apiCall<JournalEntry>(`/journal/date/${date}`);
  } catch {
    return undefined;
  }
}

// ========== REFLECTIONS ==========
export async function getReflections(): Promise<Reflection[]> {
  try {
    return await apiCall<Reflection[]>('/reflections');
  } catch {
    return [];
  }
}

export async function saveReflections(reflections: Reflection[]): Promise<void> {
  await apiCall('/reflections', {
    method: 'PUT',
    body: JSON.stringify(reflections),
  });
}

export async function addReflection(reflection: Omit<Reflection, 'id' | 'createdAt'>): Promise<Reflection> {
  return await apiCall<Reflection>('/reflections', {
    method: 'POST',
    body: JSON.stringify(reflection),
  });
}

export async function getReflectionByDate(date: string): Promise<Reflection | undefined> {
  try {
    return await apiCall<Reflection>(`/reflections/date/${date}`);
  } catch {
    return undefined;
  }
}

// ========== CHAT HISTORY ==========
export async function getChatHistory(): Promise<ChatMessage[]> {
  try {
    return await apiCall<ChatMessage[]>('/chat');
  } catch {
    return [];
  }
}

export async function saveChatHistory(messages: ChatMessage[]): Promise<void> {
  await apiCall('/chat', {
    method: 'PUT',
    body: JSON.stringify(messages),
  });
}

export async function addChatMessage(message: Omit<ChatMessage, 'id' | 'timestamp'>): Promise<ChatMessage> {
  return await apiCall<ChatMessage>('/chat', {
    method: 'POST',
    body: JSON.stringify(message),
  });
}

export async function clearChatHistory(): Promise<void> {
  await apiCall('/chat', { method: 'DELETE' });
}

// ========== ACHIEVEMENTS ==========
const defaultAchievements: Achievement[] = [
  { id: 'first_habit', title: 'First Step', description: 'Complete your first habit', icon: '🌱', category: 'milestone' },
  { id: 'streak_7', title: 'Week Warrior', description: 'Maintain a 7-day streak', icon: '🔥', category: 'streak' },
  { id: 'streak_30', title: 'Monthly Master', description: 'Maintain a 30-day streak', icon: '⭐', category: 'streak' },
  { id: 'first_reflection', title: 'Mindful Moment', description: 'Complete your first reflection', icon: '🧘', category: 'milestone' },
  { id: 'journal_10', title: 'Story Teller', description: 'Write 10 journal entries', icon: '📖', category: 'milestone' },
  { id: 'goals_3', title: 'Goal Getter', description: 'Set 3 goals', icon: '🎯', category: 'milestone' },
  { id: 'morning_prep_7', title: 'Early Bird', description: 'Complete 7 morning preps', icon: '🌅', category: 'streak' },
  { id: 'chat_coach_10', title: 'Open Mind', description: 'Have 10 coaching sessions', icon: '💬', category: 'milestone' },
];

export async function getAchievements(): Promise<Achievement[]> {
  try {
    return await apiCall<Achievement[]>('/achievements');
  } catch {
    return defaultAchievements;
  }
}

export async function unlockAchievement(id: string): Promise<void> {
  await apiCall(`/achievements/${id}/unlock`, { method: 'POST' });
}

// ========== SETTINGS ==========
const defaultSettings: Settings = {
  notifications: true,
  morningPrepTime: '07:00',
  eveningReflectionTime: '21:00',
  theme: 'light',
  privacy: {
    shareAnalytics: false,
    showStreak: true,
  },
};

export async function getSettings(): Promise<Settings> {
  try {
    return await apiCall<Settings>('/settings');
  } catch {
    return defaultSettings;
  }
}

export async function saveSettings(settings: Settings): Promise<void> {
  await apiCall('/settings', {
    method: 'PUT',
    body: JSON.stringify(settings),
  });
}

// ========== ONBOARDING ==========
export async function isOnboardingComplete(): Promise<boolean> {
  try {
    const result = await apiCall<{ complete: boolean }>('/onboarding');
    return result.complete;
  } catch {
    return false;
  }
}

export async function setOnboardingComplete(): Promise<void> {
  await apiCall('/onboarding', { method: 'POST' });
}

// Helper to get today's date string
export const getTodayString = () => getToday();
