// LocalStorage keys
const KEYS = {
  USER: 'justly_user',
  GOALS: 'justly_goals',
  HABITS: 'justly_habits',
  TASKS: 'justly_tasks',
  JOURNAL: 'justly_journal',
  REFLECTIONS: 'justly_reflections',
  CHAT_HISTORY: 'justly_chat_history',
  ACHIEVEMENTS: 'justly_achievements',
  SETTINGS: 'justly_settings',
  ONBOARDING_COMPLETE: 'justly_onboarding_complete',
};

export interface User {
  id: string;
  name: string;
  email: string;
  avatar?: string;
  createdAt: string;
}

export interface Goal {
  id: string;
  title: string;
  description: string;
  category: 'health' | 'career' | 'wellness' | 'relationships' | 'personal';
  targetDate?: string;
  createdAt: string;
  progress: number;
}

export interface Habit {
  id: string;
  title: string;
  description?: string;
  category: 'health' | 'productivity' | 'mindfulness' | 'social' | 'learning';
  frequency: 'daily' | 'weekly' | 'custom';
  completedDates: string[];
  streak: number;
  createdAt: string;
  goalId?: string;
  icon?: string;
  color?: string;
}

export interface Task {
  id: string;
  title: string;
  description?: string;
  completed: boolean;
  date: string;
  habitId?: string;
  goalId?: string;
  priority: 'low' | 'medium' | 'high';
  createdAt: string;
}

export interface JournalEntry {
  id: string;
  date: string;
  content: string;
  mood: 'great' | 'good' | 'okay' | 'low' | 'difficult';
  tags: string[];
  autoGenerated: boolean;
  chatSummary?: string;
  reflectionSummary?: string;
  createdAt: string;
}

export interface Reflection {
  id: string;
  date: string;
  wins: string[];
  challenges: string[];
  gratitude: string[];
  lessonsLearned: string;
  mood: 'great' | 'good' | 'okay' | 'low' | 'difficult';
  energyLevel: number;
  createdAt: string;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
}

export interface Achievement {
  id: string;
  title: string;
  description: string;
  icon: string;
  unlockedAt?: string;
  category: 'streak' | 'milestone' | 'special';
}

export interface Settings {
  notifications: boolean;
  morningPrepTime: string;
  eveningReflectionTime: string;
  theme: 'light' | 'dark' | 'system';
  privacy: {
    shareAnalytics: boolean;
    showStreak: boolean;
  };
}

// Helper functions
const generateId = () => Math.random().toString(36).substring(2, 15);

const getToday = () => new Date().toISOString().split('T')[0];

// User
export const getUser = (): User | null => {
  const data = localStorage.getItem(KEYS.USER);
  return data ? JSON.parse(data) : null;
};

export const setUser = (user: User) => {
  localStorage.setItem(KEYS.USER, JSON.stringify(user));
};

export const createUser = (name: string, email: string, password: string): User => {
  const user: User = {
    id: generateId(),
    name,
    email,
    createdAt: new Date().toISOString(),
  };
  // Store password hash (in real app, this would be server-side)
  localStorage.setItem(`justly_auth_${email}`, btoa(password));
  setUser(user);
  return user;
};

export const loginUser = (email: string, password: string): User | null => {
  const storedPassword = localStorage.getItem(`justly_auth_${email}`);
  if (storedPassword && atob(storedPassword) === password) {
    const user = getUser();
    if (user && user.email === email) {
      return user;
    }
    // Check if user exists in any stored user
    const allUsers = getAllUsers();
    const matchedUser = allUsers.find(u => u.email === email);
    if (matchedUser) {
      setUser(matchedUser);
      return matchedUser;
    }
  }
  return null;
};

const getAllUsers = (): User[] => {
  const users: User[] = [];
  for (let i = 0; i < localStorage.length; i++) {
    const key = localStorage.key(i);
    if (key?.startsWith('justly_user_')) {
      const data = localStorage.getItem(key);
      if (data) users.push(JSON.parse(data));
    }
  }
  const currentUser = getUser();
  if (currentUser) users.push(currentUser);
  return users;
};

export const logoutUser = () => {
  localStorage.removeItem(KEYS.USER);
  localStorage.removeItem(KEYS.ONBOARDING_COMPLETE);
};

// Goals
export const getGoals = (): Goal[] => {
  const data = localStorage.getItem(KEYS.GOALS);
  return data ? JSON.parse(data) : [];
};

export const saveGoals = (goals: Goal[]) => {
  localStorage.setItem(KEYS.GOALS, JSON.stringify(goals));
};

export const addGoal = (goal: Omit<Goal, 'id' | 'createdAt' | 'progress'>): Goal => {
  const newGoal: Goal = {
    ...goal,
    id: generateId(),
    createdAt: new Date().toISOString(),
    progress: 0,
  };
  const goals = getGoals();
  goals.push(newGoal);
  saveGoals(goals);
  return newGoal;
};

export const updateGoal = (id: string, updates: Partial<Goal>) => {
  const goals = getGoals();
  const index = goals.findIndex(g => g.id === id);
  if (index !== -1) {
    goals[index] = { ...goals[index], ...updates };
    saveGoals(goals);
  }
};

export const deleteGoal = (id: string) => {
  const goals = getGoals().filter(g => g.id !== id);
  saveGoals(goals);
};

// Habits
export const getHabits = (): Habit[] => {
  const data = localStorage.getItem(KEYS.HABITS);
  return data ? JSON.parse(data) : [];
};

export const saveHabits = (habits: Habit[]) => {
  localStorage.setItem(KEYS.HABITS, JSON.stringify(habits));
};

export const addHabit = (habit: Omit<Habit, 'id' | 'createdAt' | 'completedDates' | 'streak'>): Habit => {
  const newHabit: Habit = {
    ...habit,
    id: generateId(),
    createdAt: new Date().toISOString(),
    completedDates: [],
    streak: 0,
  };
  const habits = getHabits();
  habits.push(newHabit);
  saveHabits(habits);
  return newHabit;
};

export const completeHabit = (id: string) => {
  const habits = getHabits();
  const habit = habits.find(h => h.id === id);
  if (habit) {
    const today = getToday();
    if (!habit.completedDates.includes(today)) {
      habit.completedDates.push(today);
      // Calculate streak
      const yesterday = new Date();
      yesterday.setDate(yesterday.getDate() - 1);
      const yesterdayStr = yesterday.toISOString().split('T')[0];
      if (habit.completedDates.includes(yesterdayStr)) {
        habit.streak += 1;
      } else {
        habit.streak = 1;
      }
      saveHabits(habits);
    }
  }
};

export const uncompleteHabit = (id: string) => {
  const habits = getHabits();
  const habit = habits.find(h => h.id === id);
  if (habit) {
    const today = getToday();
    habit.completedDates = habit.completedDates.filter(d => d !== today);
    saveHabits(habits);
  }
};

export const deleteHabit = (id: string) => {
  const habits = getHabits().filter(h => h.id !== id);
  saveHabits(habits);
};

// Tasks
export const getTasks = (date?: string): Task[] => {
  const data = localStorage.getItem(KEYS.TASKS);
  const tasks: Task[] = data ? JSON.parse(data) : [];
  if (date) {
    return tasks.filter(t => t.date === date);
  }
  return tasks;
};

export const saveTasks = (tasks: Task[]) => {
  localStorage.setItem(KEYS.TASKS, JSON.stringify(tasks));
};

export const addTask = (task: Omit<Task, 'id' | 'createdAt'>): Task => {
  const newTask: Task = {
    ...task,
    id: generateId(),
    createdAt: new Date().toISOString(),
  };
  const tasks = getTasks();
  tasks.push(newTask);
  saveTasks(tasks);
  return newTask;
};

export const toggleTask = (id: string) => {
  const tasks = getTasks();
  const task = tasks.find(t => t.id === id);
  if (task) {
    task.completed = !task.completed;
    saveTasks(tasks);
  }
};

export const deleteTask = (id: string) => {
  const tasks = getTasks().filter(t => t.id !== id);
  saveTasks(tasks);
};

// Journal
export const getJournalEntries = (): JournalEntry[] => {
  const data = localStorage.getItem(KEYS.JOURNAL);
  return data ? JSON.parse(data) : [];
};

export const saveJournalEntries = (entries: JournalEntry[]) => {
  localStorage.setItem(KEYS.JOURNAL, JSON.stringify(entries));
};

export const addJournalEntry = (entry: Omit<JournalEntry, 'id' | 'createdAt'>): JournalEntry => {
  const newEntry: JournalEntry = {
    ...entry,
    id: generateId(),
    createdAt: new Date().toISOString(),
  };
  const entries = getJournalEntries();
  entries.unshift(newEntry);
  saveJournalEntries(entries);
  return newEntry;
};

export const getJournalByDate = (date: string): JournalEntry | undefined => {
  return getJournalEntries().find(e => e.date === date);
};

// Reflections
export const getReflections = (): Reflection[] => {
  const data = localStorage.getItem(KEYS.REFLECTIONS);
  return data ? JSON.parse(data) : [];
};

export const saveReflections = (reflections: Reflection[]) => {
  localStorage.setItem(KEYS.REFLECTIONS, JSON.stringify(reflections));
};

export const addReflection = (reflection: Omit<Reflection, 'id' | 'createdAt'>): Reflection => {
  const newReflection: Reflection = {
    ...reflection,
    id: generateId(),
    createdAt: new Date().toISOString(),
  };
  const reflections = getReflections();
  reflections.unshift(newReflection);
  saveReflections(reflections);
  return newReflection;
};

export const getReflectionByDate = (date: string): Reflection | undefined => {
  return getReflections().find(r => r.date === date);
};

// Chat History
export const getChatHistory = (): ChatMessage[] => {
  const data = localStorage.getItem(KEYS.CHAT_HISTORY);
  return data ? JSON.parse(data) : [];
};

export const saveChatHistory = (messages: ChatMessage[]) => {
  localStorage.setItem(KEYS.CHAT_HISTORY, JSON.stringify(messages));
};

export const addChatMessage = (message: Omit<ChatMessage, 'id' | 'timestamp'>): ChatMessage => {
  const newMessage: ChatMessage = {
    ...message,
    id: generateId(),
    timestamp: new Date().toISOString(),
  };
  const history = getChatHistory();
  history.push(newMessage);
  saveChatHistory(history);
  return newMessage;
};

export const clearChatHistory = () => {
  localStorage.removeItem(KEYS.CHAT_HISTORY);
};

// Achievements
export const getAchievements = (): Achievement[] => {
  const data = localStorage.getItem(KEYS.ACHIEVEMENTS);
  return data ? JSON.parse(data) : defaultAchievements;
};

export const unlockAchievement = (id: string) => {
  const achievements = getAchievements();
  const achievement = achievements.find(a => a.id === id);
  if (achievement && !achievement.unlockedAt) {
    achievement.unlockedAt = new Date().toISOString();
    localStorage.setItem(KEYS.ACHIEVEMENTS, JSON.stringify(achievements));
  }
};

const defaultAchievements: Achievement[] = [
  { id: 'first_habit', title: 'First Step', description: 'Complete your first habit', icon: '🌱', category: 'milestone' },
  { id: 'streak_7', title: 'Week Warrior', description: 'Maintain a 7-day streak', icon: '🔥', category: 'streak' },
  { id: 'streak_30', title: 'Monthly Master', description: 'Maintain a 30-day streak', icon: '⭐', category: 'streak' },
  { id: 'first_reflection', title: 'Mindful Moment', description: 'Complete your first reflection', icon: '🧘', category: 'milestone' },
  { id: 'journal_10', title: 'Story Teller', description: 'Write 10 journal entries', icon: '📖', category: 'milestone' },
  { id: 'goals_3', title: 'Goal Getter', description: 'Set 3 goals', icon: '🎯', category: 'milestone' },
  { id: 'morning_prep_7', title: 'Early Bird', description: 'Complete 7 morning preps', icon: '🌅', category: 'streak' },
  { id: 'chat_coach_10', title: 'Open Mind', description: 'Have 10 coaching sessions', icon: '💬', category: 'milestone' },
];

// Settings
export const getSettings = (): Settings => {
  const data = localStorage.getItem(KEYS.SETTINGS);
  return data ? JSON.parse(data) : defaultSettings;
};

export const saveSettings = (settings: Settings) => {
  localStorage.setItem(KEYS.SETTINGS, JSON.stringify(settings));
};

const defaultSettings: Settings = {
  notifications: true,
  morningPrepTime: '07:00',
  eveningReflectionTime: '21:00',
  theme: 'light',
  privacy: {
    shareAnalytics: false,
    showStreak: true,
  },
};

// Onboarding
export const isOnboardingComplete = (): boolean => {
  return localStorage.getItem(KEYS.ONBOARDING_COMPLETE) === 'true';
};

export const setOnboardingComplete = () => {
  localStorage.setItem(KEYS.ONBOARDING_COMPLETE, 'true');
};

// Helper to get today's date string
export const getTodayString = () => getToday();
