import { useState, useEffect, useCallback } from 'react';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { addReflection, addJournalEntry, getReflections, getJournalEntries, getTodayString, getHabits, getTasks, getChatHistory, JournalEntry, Reflection } from '@/lib/storage';
import { generateJournalEntry, generateReflectionPrompts } from '@/lib/gemini';
import { toast } from '@/hooks/use-toast';
import { Plus, Target, MessageCircle, Sparkles, Moon, User, BookOpen, Loader2 } from 'lucide-react';

const moods = [
  { value: 'great', emoji: '😄', label: 'Great' },
  { value: 'good', emoji: '🙂', label: 'Good' },
  { value: 'okay', emoji: '😐', label: 'Okay' },
  { value: 'low', emoji: '😔', label: 'Low' },
  { value: 'difficult', emoji: '😢', label: 'Difficult' },
] as const;

const Reflect = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [mood, setMood] = useState<typeof moods[number]['value']>('good');
  const [wins, setWins] = useState('');
  const [challenges, setChallenges] = useState('');
  const [lessons, setLessons] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [isDataLoading, setIsDataLoading] = useState(true);
  const [prompts, setPrompts] = useState<string[]>([]);
  const [journals, setJournals] = useState<JournalEntry[]>([]);
  
  const today = getTodayString();

  const loadData = useCallback(async () => {
    try {
      const journalsData = await getJournalEntries();
      setJournals(journalsData);
    } catch (error) {
      console.error('Failed to load data:', error);
    } finally {
      setIsDataLoading(false);
    }
  }, []);

  useEffect(() => {
    loadData();
  }, [loadData]);

  const loadPrompts = async () => {
    const [tasks, habits] = await Promise.all([getTasks(today), getHabits()]);
    const generated = await generateReflectionPrompts(mood, tasks.filter(t => t.completed).length, habits.map(h => h.title));
    setPrompts(generated);
  };

  const handleSave = async () => {
    setIsLoading(true);
    try {
      const reflection = await addReflection({
        date: today,
        wins: wins.split('\n').filter(Boolean),
        challenges: challenges.split('\n').filter(Boolean),
        gratitude: [],
        lessonsLearned: lessons,
        mood,
        energyLevel: 5,
      });

      const [tasks, chatHistory] = await Promise.all([getTasks(today), getChatHistory()]);
      const journalContent = await generateJournalEntry(
        chatHistory.slice(-10).map(m => ({ role: m.role, content: m.content })),
        { wins: reflection.wins, challenges: reflection.challenges, mood, lessonsLearned: lessons },
        tasks.filter(t => t.completed).length,
        tasks.length
      );

      await addJournalEntry({
        date: today,
        content: journalContent,
        mood,
        tags: [],
        autoGenerated: true,
        reflectionSummary: lessons,
      });

      await loadData();
      toast({ title: 'Reflection saved!', description: 'Your journal entry has been created.' });
      setIsOpen(false);
      setWins(''); setChallenges(''); setLessons('');
    } catch (error) {
      toast({ title: 'Error', description: 'Failed to save reflection.', variant: 'destructive' });
    }
    setIsLoading(false);
  };

  if (isDataLoading) {
    return (
      <div className="min-h-screen gradient-calm flex items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <div className="min-h-screen gradient-calm pb-24">
      <header className="container mx-auto px-4 py-6">
        <div className="flex items-center justify-between">
          <h1 className="text-2xl font-bold text-foreground">Reflect</h1>
          <Dialog open={isOpen} onOpenChange={setIsOpen}>
            <DialogTrigger asChild><Button variant="hero" size="icon"><Plus className="h-5 w-5" /></Button></DialogTrigger>
            <DialogContent className="max-h-[90vh] overflow-y-auto">
              <DialogHeader><DialogTitle>Evening Reflection</DialogTitle></DialogHeader>
              <div className="space-y-4 pt-4">
                <div>
                  <p className="text-sm font-medium mb-2">How are you feeling?</p>
                  <div className="flex gap-2">
                    {moods.map(m => (
                      <button key={m.value} onClick={() => setMood(m.value)} className={`flex-1 p-2 rounded-lg border-2 transition-all ${mood === m.value ? 'border-primary bg-primary/10' : 'border-border'}`}>
                        <span className="text-2xl">{m.emoji}</span>
                        <p className="text-xs mt-1">{m.label}</p>
                      </button>
                    ))}
                  </div>
                </div>
                <div><p className="text-sm font-medium mb-2">What went well today?</p><Textarea placeholder="Your wins, big or small..." value={wins} onChange={(e) => setWins(e.target.value)} rows={3} /></div>
                <div><p className="text-sm font-medium mb-2">What challenges did you face?</p><Textarea placeholder="Any obstacles or struggles..." value={challenges} onChange={(e) => setChallenges(e.target.value)} rows={3} /></div>
                <div><p className="text-sm font-medium mb-2">What did you learn?</p><Textarea placeholder="Insights or lessons..." value={lessons} onChange={(e) => setLessons(e.target.value)} rows={3} /></div>
                {prompts.length > 0 && (
                  <div className="bg-secondary/50 p-3 rounded-lg">
                    <p className="text-xs font-medium text-muted-foreground mb-2">💡 Reflection prompts:</p>
                    {prompts.map((p, i) => <p key={i} className="text-sm text-foreground">• {p}</p>)}
                  </div>
                )}
                <div className="flex gap-2">
                  <Button variant="outline" className="flex-1" onClick={loadPrompts}>Get Prompts</Button>
                  <Button variant="hero" className="flex-1" onClick={handleSave} disabled={isLoading}>
                    {isLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : 'Save Reflection'}
                  </Button>
                </div>
              </div>
            </DialogContent>
          </Dialog>
        </div>
      </header>

      <main className="container mx-auto px-4 space-y-6">
        <Card variant="soft" className="text-center py-8">
          <Moon className="h-12 w-12 text-gentle-lavender mx-auto mb-3" />
          <h2 className="font-semibold text-foreground mb-1">Evening Reflection</h2>
          <p className="text-sm text-muted-foreground mb-4">Take a moment to reflect on your day</p>
          <Button variant="hero" onClick={() => setIsOpen(true)}>Start Reflection</Button>
        </Card>

        <div>
          <h2 className="text-lg font-semibold text-foreground mb-3 flex items-center gap-2"><BookOpen className="h-5 w-5" /> Journal</h2>
          {journals.length === 0 ? (
            <Card variant="soft"><CardContent className="py-8 text-center"><p className="text-muted-foreground">Your journal entries will appear here after reflections.</p></CardContent></Card>
          ) : (
            <div className="space-y-3">
              {journals.slice(0, 5).map(j => (
                <Card key={j.id}>
                  <CardHeader className="pb-2"><CardTitle className="text-sm flex items-center justify-between"><span>{new Date(j.date).toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' })}</span><span>{moods.find(m => m.value === j.mood)?.emoji}</span></CardTitle></CardHeader>
                  <CardContent><p className="text-sm text-muted-foreground line-clamp-3">{j.content}</p></CardContent>
                </Card>
              ))}
            </div>
          )}
        </div>
      </main>

      <nav className="fixed bottom-0 left-0 right-0 bg-card border-t border-border">
        <div className="container mx-auto px-4"><div className="flex justify-around py-3">
          <Link to="/home" className="flex flex-col items-center text-muted-foreground hover:text-primary"><Target className="h-5 w-5" /><span className="text-xs mt-1">Home</span></Link>
          <Link to="/coach" className="flex flex-col items-center text-muted-foreground hover:text-primary"><MessageCircle className="h-5 w-5" /><span className="text-xs mt-1">Coach</span></Link>
          <Link to="/habits" className="flex flex-col items-center text-muted-foreground hover:text-primary"><Sparkles className="h-5 w-5" /><span className="text-xs mt-1">Habits</span></Link>
          <Link to="/reflect" className="flex flex-col items-center text-primary"><Moon className="h-5 w-5" /><span className="text-xs mt-1">Reflect</span></Link>
          <Link to="/profile" className="flex flex-col items-center text-muted-foreground hover:text-primary"><User className="h-5 w-5" /><span className="text-xs mt-1">Profile</span></Link>
        </div></div>
      </nav>
    </div>
  );
};

export default Reflect;
